config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :books do
        get :archived, on: :collection
        put :archive, on: :member
        put :unarchive, on: :member
      end
    end
  end
  # Defines the root path route ("/")
  root "books#index"
  get "/publications", to: redirect("/books")

  resources :books do
    get :archived, on: :collection
    put :archive, on: :member
    put :unarchive, on: :member
  end
end

app/models/api/v1.rb
module Api::V1
  def self.table_name_prefix
    "api_v1_"
  end
end

app/models/api/v1/book.rb
class Api::V1::Book < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true, length: { maximum: 100 }
  validates :year, presence: true
end

app/controllers/api/v1/books_controller.rb
class Api::V1::BooksController < ApplicationController
  before_action :set_api_v1_book, only: %i[ show edit update destroy ]

  # GET /api/v1/books or /api/v1/books.json
  def index
    @api_v1_books = Api::V1::Book.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render xml: @api_v1_books }
      format.json { render json: @api_v1_books }
    end
  end

  # GET /api/v1/books/1 or /api/v1/books/1.json
  def show
    set_api_v1_book

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render xml: @api_v1_book }
      format.json { render json: @api_v1_book }
    end
  end

  # GET /api/v1/books/new
  def new
    @api_v1_book = Api::V1::Book.new
  end

  # GET /api/v1/books/1/edit
  def edit
  end

  # POST /api/v1/books or /api/v1/books.json
  def create
    @api_v1_book = Api::V1::Book.new(api_v1_book_params)

    respond_to do |format|
      if @api_v1_book.save
        format.html { redirect_to @api_v1_book, notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @api_v1_book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @api_v1_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /api/v1/books/1 or /api/v1/books/1.json
  def update
    respond_to do |format|
      if @api_v1_book.update(api_v1_book_params)
        format.html { redirect_to @api_v1_book, notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @api_v1_book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @api_v1_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /api/v1/books/1 or /api/v1/books/1.json
  def destroy
    @api_v1_book.destroy!

    respond_to do |format|
      format.html { redirect_to api_v1_books_path, status: :see_other, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def archive
    set_api_v1_book.update(archived: true)

    respond_to do |format|
      if @api_v1_book.update(api_v1_book_params)
        format.html { redirect_to api_v1_books_path, notice: "Book was successfully archived." }
        format.json { render :index, status: :see_other, location: @api_v1_books }
      else
        format.html { render :index, status: :unprocessable_entity }
        format.json { render json: @api_v1_book.errors, status: :unprocessable_entity }
      end
    end
    # redirect_to api_v1_books_path status: :see_other
  end

  def archived
    @api_v1_books = Api::V1::Book.all.where(archived: true).order(:title)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render xml: @api_v1_books }
      format.json { render json: @api_v1_books }
    end
  end

  def unarchive
    set_api_v1_book.update(archived: false)

    respond_to do |format|
      if @api_v1_book.update(api_v1_book_params)
        format.html { redirect_to api_v1_books_path, notice: "Book was successfully archived." }
        format.json { render :index, status: :see_other, location: @api_v1_books }
      else
        format.html { render :index, status: :unprocessable_entity }
        format.json { render json: @api_v1_book.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_api_v1_book
      @api_v1_book = Api::V1::Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def api_v1_book_params
      params.require(:api_v1_book).permit(:title, :author, :description, :publication_year, :archived, :old)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  # allow_browser versions: :modern
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all.where(archived: false).order(:title)
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to @book
    else
      render :new, status: unprocessable_entity
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      redirect_to @book
    else
      reder :edit, status: unprocessable_entity
    end
  end

  def destroy
    @book = Book.all.find(params[:id])
    @book.destroy

    redirect_to root_path, status: :see_other
  end

  def archive
    @book = Book.find(params[:id])
    @book.update(archived: true)

    redirect_to root_path, status: :see_other
  end

  def archived
    @books = Book.all.where(archived: true).order(:title)
  end

  def unarchive
    @book = Book.find(params[:id])
    @book.update(archived: false)

    redirect_to root_path, status: :see_other
  end

  private
    def book_params
      params.require(:book).permit(:title, :description, :year, :old, :archived)
    end
end

app/helpers/api/v1/books_helper.rb
module Api::V1::BooksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with model: book do |form| %>
    <div>
        <%= form.label :title %><br>
        <%= form.text_field :title %>
        <% book.errors.full_messages_for(:title).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :description %><br>
        <%= form.text_area :description %>
        <% book.errors.full_messages_for(:description).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :year %><br>
        <%= form.text_field :year %>
        <% book.errors.full_messages_for(:year).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :old %><br>
        <%= form.check_box :old, as: :boolean %>
        <% book.errors.full_messages_for(:old).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :archived %><br>
        <%= form.check_box :archived, as: :boolean %>
        <% book.errors.full_messages_for(:archived).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/books/archived.html.erb
<h1>Archived Book List</h1>
<ul>
    <% @books.each do |book| %>
    <li>
        <%= link_to book.title, book %>
        <%= button_to "Unarchive", unarchive_book_path(book), method: :put %>
    </li>
    <% end %>
</ul>

<%= link_to "Home", root_path %>

app/views/books/edit.html.erb
<h1>Edit Book</h1>

<%= render "form", book: @book %>

app/views/books/index.html.erb
<h1>Book List</h1>
<table>
    <% @books.each do |book| %>
    <tr>
        <td>
            <%= link_to book.title, book %>
        </td>
        <td>
            <% if book.old %>
            <p> Old </p>
            <% else %>
            <p> New! </p>
            <% end %>
        </td>
        <td>
            <%= button_to "Archive", archive_book_path(book), method: :put  %>
        </td>
    </tr>
    <% end %>
</table>

<%= link_to "New Book", new_book_path %>
<%= link_to "Archived Books", archived_books_path %>

app/views/books/new.html.erb
<%= link_to "Home", root_path %>

<h1>New Book</h1>

<%= render "form", book: @book %>

app/views/books/show.html.erb
<%= link_to "Home", root_path %>

<h1><%= @book.title %></h1>

<% if @book.old %>
<p>Old</p>
<% else %>
<p>New!</p>
<% end %>

<p><%= @book.description %></p>

<ul>
    <li><%= button_to "Archive", archive_book_path(@book), method: :put %></li>
    <li><%= link_to "Edit", edit_book_path(@book) %></li>
    <li><%= link_to "Destroy", book_path(@book), data: {
                        turbo_method: :delete,
                        turbo_confirm: "Are you sure?"
                    } %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Book" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>